# -*- coding: utf-8 -*-
"""AI_Productivity_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c38v6xRR1VbpVXf1OwFHZkXVIpP0-EB0
"""

# AI PRODUCTIVITY DASHBOARD
# Created by: DIVYANSHI SAXENA 23102078

import os
import json
import requests
import datetime
import random

try:
    import wikipediaapi
except Exception:
    wikipediaapi = None

try:
    import matplotlib.pyplot as plt
except Exception:
    plt = None

DATA_DIR = "data"
TASKS_FILE = os.path.join(DATA_DIR, "tasks.json")
NOTES_DIR = os.path.join(DATA_DIR, "notes")


# ------------------ Initialization ------------------
def init_storage():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(NOTES_DIR, exist_ok=True)
    if not os.path.exists(TASKS_FILE):
        with open(TASKS_FILE, "w", encoding="utf-8") as f:
            json.dump([], f)


def load_tasks():
    try:
        with open(TASKS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return []


def save_tasks(tasks):
    with open(TASKS_FILE, "w", encoding="utf-8") as f:
        json.dump(tasks, f, indent=2)


# ------------------ Task Manager ------------------
def add_task():
    title = input("Enter task title: ").strip()
    if not title:
        print("Task title cannot be empty.")
        return
    due_input = input("Enter due date (YYYY-MM-DD) or leave blank: ").strip()
    due_date = None
    if due_input:
        try:
            due_date = datetime.datetime.strptime(due_input, "%Y-%m-%d").date().isoformat()
        except:
            print("Invalid date. Saving without due date.")

    tasks = load_tasks()
    task = {
        "id": random.randint(1000, 9999),
        "title": title,
        "created": datetime.date.today().isoformat(),
        "due": due_date,
        "done": False
    }
    tasks.append(task)
    save_tasks(tasks)
    print("✅ Task added successfully!")


def view_tasks(show_all=True):
    tasks = load_tasks()
    if not tasks:
        print("No tasks available.")
        return
    print("\n📋 Your Tasks:\n")
    for i, t in enumerate(tasks, start=1):
        status = "✅ Done" if t["done"] else "🕒 Pending"
        due = t["due"] or "No due date"
        if show_all or not t["done"]:
            print(f"{i}. {t['title']} | {status} | Due: {due}")
    print("")


def mark_task_done():
    tasks = load_tasks()
    view_tasks()
    if not tasks:
        return
    try:
        idx = int(input("Enter task number to mark as done: "))
        if 1 <= idx <= len(tasks):
            tasks[idx - 1]["done"] = True
            save_tasks(tasks)
            print("✅ Task marked as done!")
        else:
            print("Invalid number.")
    except:
        print("Invalid input.")


def delete_task():
    tasks = load_tasks()
    view_tasks()
    if not tasks:
        return
    try:
        idx = int(input("Enter task number to delete: "))
        if 1 <= idx <= len(tasks):
            removed = tasks.pop(idx - 1)
            save_tasks(tasks)
            print(f"🗑 Deleted task: {removed['title']}")
        else:
            print("Invalid number.")
    except:
        print("Invalid input.")


# ------------------ Notes Manager ------------------
def add_note():
    title = input("Enter note title: ").strip()
    if not title:
        print("Title cannot be empty.")
        return
    print("Enter note content (press Enter twice to finish):")
    lines = []
    while True:
        line = input()
        if not line:
            break
        lines.append(line)
    content = "\n".join(lines)
    filename = os.path.join(NOTES_DIR, f"{title.replace(' ', '_')}.txt")
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"NOTE TITLE: {title}\nBy: DIVYANSHI SAXENA 23102078\n\n{content}")
    print(f"✅ Note saved as '{filename}'")


def list_notes():
    files = [f for f in os.listdir(NOTES_DIR) if f.endswith(".txt")]
    if not files:
        print("No notes found.")
        return
    print("\n🗂 Notes List:")
    for i, f in enumerate(files, start=1):
        print(f"{i}. {f}")
    ch = input("\nEnter note number to read or press Enter to return: ").strip()
    if ch:
        try:
            idx = int(ch)
            if 1 <= idx <= len(files):
                with open(os.path.join(NOTES_DIR, files[idx - 1]), "r", encoding="utf-8") as f:
                    print("\n" + f.read() + "\n")
            else:
                print("Invalid note number.")
        except:
            print("Invalid input.")


# ------------------ Weather Widget ------------------
def fetch_weather(city):
    try:
        print(f"\nFetching live weather for '{city}'...\n")
        url = f"https://wttr.in/{city}?format=j1"
        data = requests.get(url).json()
        area = data['nearest_area'][0]['areaName'][0]['value']
        temp = data['current_condition'][0]['temp_C']
        feels = data['current_condition'][0]['FeelsLikeC']
        humidity = data['current_condition'][0]['humidity']
        desc = data['current_condition'][0]['weatherDesc'][0]['value']

        print(f"📍 Location: {area}")
        print(f"🌡 Temperature: {temp}°C (Feels like {feels}°C)")
        print(f"💧 Humidity: {humidity}%")
        print(f"🌈 Condition: {desc}")
    except:
        print("❌ Error fetching weather. Check your internet or city name.")


# ------------------ Study Assistant ------------------
def fetch_summary(topic):
    if wikipediaapi is None:
        print("Please install wikipedia-api first.")
        return "No summary available."
    wiki = wikipediaapi.Wikipedia(
        language="en",
        user_agent="AI Productivity Dashboard - DIVYANSHI SAXENA 23102078"
    )
    page = wiki.page(topic)
    if not page.exists():
        return "Sorry, topic not found."
    summary = page.summary.split(". ")
    return ". ".join(summary[:5]) + "."


def study_assistant():
    topic = input("Enter a topic: ").strip()
    summary = fetch_summary(topic)
    print("\n📘 SUMMARY:\n" + summary + "\n")
    key_terms = [w for w in summary.split() if w.istitle()][:3]
    for k in key_terms:
        print(f"Q: What do you know about {k}?")
        print(f"A: {k} is an important concept from this topic.\n")


# ------------------ Stats (Non-blocking Graph) ------------------
def show_stats():
    tasks = load_tasks()
    total = len(tasks)
    done = sum(1 for t in tasks if t["done"])
    pending = total - done
    notes_count = len([f for f in os.listdir(NOTES_DIR) if f.endswith(".txt")])

    print("\n📊 Dashboard Stats:")
    print(f"Total tasks: {total}")
    print(f"Completed: {done}")
    print(f"Pending: {pending}")
    print(f"Saved notes: {notes_count}")

    if plt:
        labels = ["Completed", "Pending", "Notes"]
        values = [done, pending, notes_count]
        plt.figure(figsize=(6, 4))
        plt.bar(labels, values, color=["green", "orange", "blue"])
        plt.title("AI Productivity Dashboard Summary")
        plt.ylabel("Count")
        plt.tight_layout()
        # Non-blocking display
        plt.show(block=False)
        plt.pause(3)
        plt.close()

    input("\nPress Enter to return to the main menu...")


# ------------------ Main Menu ------------------
def main_menu():
    init_storage()
    while True:
        print("\n=== AI Productivity Dashboard ===")
        print("1. Manage Tasks")
        print("2. Notes")
        print("3. Weather")
        print("4. Study Assistant")
        print("5. View Stats")
        print("6. Exit")
        choice = input("Enter choice (1-6): ").strip()

        if choice == '1':
            while True:
                print("\n--- Task Menu ---")
                print("a. Add Task")
                print("b. View Tasks")
                print("c. Mark Done")
                print("d. Delete Task")
                print("e. Back")
                ch = input("Select (a-e): ").strip().lower()
                if ch == 'a':
                    add_task()
                elif ch == 'b':
                    view_tasks()
                elif ch == 'c':
                    mark_task_done()
                elif ch == 'd':
                    delete_task()
                elif ch == 'e':
                    break
                else:
                    print("Invalid option.")
        elif choice == '2':
            while True:
                print("\n--- Notes Menu ---")
                print("a. Add Note")
                print("b. List Notes")
                print("c. Back")
                ch = input("Select (a-c): ").strip().lower()
                if ch == 'a':
                    add_note()
                elif ch == 'b':
                    list_notes()
                elif ch == 'c':
                    break
        elif choice == '3':
            city = input("Enter city name: ")
            fetch_weather(city)
        elif choice == '4':
            study_assistant()
        elif choice == '5':
            show_stats()
        elif choice == '6':
            print("\n✨ SESSION SUMMARY ✨")
            tasks = load_tasks()
            done = sum(1 for t in tasks if t["done"])
            notes_count = len([f for f in os.listdir(NOTES_DIR) if f.endswith(".txt")])
            print(f"Tasks completed: {done}")
            print(f"Notes saved: {notes_count}")
            print("Great work today, Divyanshi ma’am! 🌸")
            break
        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main_menu()